
name: Java CI with Maven

on:
  push:
  
    branches: master
  pull_request:
    branches: master


permissions:
  contents: write
  security-events: write


jobs:
  build:
    env:
      user: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
      token: ${{ secrets.GITTOKEN }}

      
    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

      #Here we start to build docker image and later push it to docker hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:latest .


    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_REPOSITORY }}:latest


    - name: Log out from Docker Hub
      run: docker logout


      # I dont even know what this is but lets keep it there just in case
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
